name: Algo Trading Automation

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 03:00 UTC
  workflow_dispatch: # Allow manual run

jobs:
  run-trading:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy ta matplotlib gspread google-auth

      - name: Create service account key file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service_account.json

      - name: Run backtest script
        run: python algo_trading.py

      
