name: Algo Trading Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"   # Runs every weekday at 9 AM UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account key file
        run: |
          echo "${{ secrets.GSHEET_CREDENTIALS }}" > service_account.json

      - name: Run algo_trading.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python algo_trading.py
